---
version: '3'

services:
  videojames:
    image: shamansanchez/videojames
    command: "hug -f videojames.py"
    labels:
      - 'traefik.backend=videojames'
      - 'traefik.frontend.rule=Host: videojames.shamansanchez.com'
    volumes:
      - /etc/videojames/token:/etc/videojames/token
      - /etc/videojames/db:/app/videojames.db
    restart: always
